version: '3.8'

services:
  mailhog:
    image: axllent/mailpit:latest
    container_name: climalert-mailpit
    ports:
      - "1025:1025" # Puerto SMTP de Mailpit
      - "8025:8025" # Puerto de la interfaz web de Mailpit
    restart: unless-stopped
