# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:climalertdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración básica de Correo (Spring Mail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@example.com
spring.mail.password=your-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración de la API Meteorológica (WeatherAPI)
weather.api.url=https://api.weatherapi.com/v1
weather.api.key=cdecb9bf8f094295ac0203932260607
weather.api.location=CABA

# Configuración de los destinatarios de alertas por correo
weather.alerts.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com
